In [2]:
import sqlite3
import pandas as pd

con = sqlite3.connect('C:\\Users\\jasee\\Downloads\\project_3.1\\2_IPL_Cricket\\ipl.db')

def q(sql):
    return pd.read_sql_query(sql, con)

In [3]:
q("""select * 
from venues ;""")

,venue_id,venue,city
0,1,M Chinnaswamy Stadium,Bangalore
1,2,"Rajiv Gandhi International Stadium, Uppal",Hyderabad
2,3,Maharashtra Cricket Association Stadium,Pune
3,4,Saurashtra Cricket Association Stadium,Rajkot
4,5,Holkar Cricket Stadium,Indore
...,...,...,...
58,59,Subrata Roy Sahara Stadium,Pune
59,60,Shaheed Veer Narayan Singh International Stadium,Raipur
60,61,JSCA International Stadium Complex,Ranchi
61,62,Maharaja Yadavindra Singh International Cricke...,New Chandigarh
62,63,Maharaja Yadavindra Singh International Cricke...,New Chandigarh

In [4]:
q("""select * 
from matches ;""")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,Kolkata Knight Riders,140.0,NaN,win,BB McCullum,1,6,1,6,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Sunrisers Hyderabad,35.0,NaN,win,Yuvraj Singh,2,1,1,2,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,NaN,7.0,win,SPD Smith,4,3,4,4,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,NaN,10.0,win,CA Lynn,5,6,6,6,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,GJ Maxwell,494,4,494,494,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,2026,6,Delhi,2026-04-27,Indian Premier League,39.0,male,T20,T20,...,Royal Challengers Bangalore,NaN,9.0,win,JR Hazlewood,252,1,1,1,4664.0
1208,1529283,2026,6,New Chandigarh,2026-04-28,Indian Premier League,40.0,male,T20,T20,...,Rajasthan Royals,NaN,6.0,win,D Ferreira,494,134,134,134,11389.0
1209,1529284,2026,6,Mumbai,2026-04-29,Indian Premier League,41.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,6.0,win,H Klaasen,3,2,3,2,1740.0
1210,1529285,2026,6,Ahmedabad,2026-04-30,Indian Premier League,42.0,male,T20,T20,...,Gujarat Titans,NaN,4.0,win,JO Holder,1,615,615,615,4098.0
1211,1529286,2026,6,Jaipur,2026-05-01,Indian Premier League,43.0,male,T20,T20,...,Delhi Capitals,NaN,7.0,win,KL Rahul,134,252,134,252,1409.0

In [5]:
q("""select * 
from deliveries ;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,1,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288221,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288222,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288223,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288224,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288225,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals

In [6]:
q("""select * 
from players ;""")

,player_id,player_name,bat_style,bowl_style,field_pos,player_full_name
0,963,MN Samuels,Right hand Bat,Right arm Offbreak,,Marlon Nathaniel Samuels
1,53,SB Jakati,Left hand Bat,Slow Left arm Orthodox,,Shadab Bashir Jakati
2,12,DA Warner,Left hand Bat,Legbreak,,David Andrew Warner
3,268,RA Tripathi,Right hand Bat,Right arm Medium,,Rahul Ajay Tripathi
4,186,S Nadeem,Right hand Bat,Slow Left arm Orthodox,,Shahbaz Nadeem
...,...,...,...,...,...,...
794,8475,Suyash Sharma,Right hand Bat,Legbreak Googly,,Suyash Sharma
795,45004,D Madushanka,Right hand Bat,Right arm Medium fast,NaN,K Dasun Madusanka
796,42566,V Suryavanshi,Left hand Bat,Slow Left arm Orthodox,NaN,Vaibhav Suryavanshi
797,26,N Rana,Left hand Bat,"Right arm Medium, Right arm Offbreak, Legbreak",,Nitish Rana
798,45986,SU Parakh,Left hand Bat,Legbreak,NaN,Sahil Ulhas Parakh

In [7]:
q("""select * 
from teams ;""")

    team_id                    team_name
0         1  Royal Challengers Bangalore
1         2          Sunrisers Hyderabad
2         3               Mumbai Indians
3         4       Rising Pune Supergiant
4         5                Gujarat Lions
5         6        Kolkata Knight Riders
6       129          Chennai Super Kings
7       134             Rajasthan Royals
8       252               Delhi Capitals
9       494                 Punjab Kings
10      614         Lucknow Super Giants
11      615               Gujarat Titans
12     1068              Deccan Chargers
13     1414         Kochi Tuskers Kerala
14     1419                Pune Warriors
15     3604      Rising Pune Supergiants

In [8]:
q("""select * from matches limit 10 ;""")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,Kolkata Knight Riders,140.0,NaN,win,BB McCullum,1,6,1,6,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Sunrisers Hyderabad,35.0,NaN,win,Yuvraj Singh,2,1,1,2,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,NaN,7.0,win,SPD Smith,4,3,4,4,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,NaN,10.0,win,CA Lynn,5,6,6,6,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,GJ Maxwell,494,4,494,494,71.0
5,1082595,2017,6,Bengaluru,2017-04-08,Indian Premier League,5.0,male,T20,T20,...,Royal Challengers Bangalore,15.0,NaN,win,KM Jadhav,1,252,1,1,4.0
6,1082596,2017,6,Hyderabad,2017-04-09,Indian Premier League,6.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,9.0,win,Rashid Khan,2,5,2,2,22.0
7,1082597,2017,6,Mumbai,2017-04-09,Indian Premier League,7.0,male,T20,T20,...,Mumbai Indians,NaN,4.0,win,N Rana,3,6,3,3,26.0
8,1082598,2017,6,Indore,2017-04-10,Indian Premier League,8.0,male,T20,T20,...,Punjab Kings,NaN,8.0,win,AR Patel,494,1,1,494,70.0
9,1082599,2017,6,Pune,2017-04-11,Indian Premier League,9.0,male,T20,T20,...,Delhi Capitals,97.0,NaN,win,SV Samson,4,252,4,252,180.0

In [9]:
q("""select match_id,city,venue from matches limit 10 ;""")

   match_id       city                                      venue
0    335982  Bangalore                      M Chinnaswamy Stadium
1   1082591  Hyderabad  Rajiv Gandhi International Stadium, Uppal
2   1082592       Pune    Maharashtra Cricket Association Stadium
3   1082593     Rajkot     Saurashtra Cricket Association Stadium
4   1082594     Indore                     Holkar Cricket Stadium
5   1082595  Bengaluru                      M.Chinnaswamy Stadium
6   1082596  Hyderabad  Rajiv Gandhi International Stadium, Uppal
7   1082597     Mumbai                           Wankhede Stadium
8   1082598     Indore                     Holkar Cricket Stadium
9   1082599       Pune    Maharashtra Cricket Association Stadium

In [10]:
q("""select distinct batsman_type from deliveries;""")

     batsman_type
0   Left hand Bat
1  Right hand Bat
2             NaN

In [11]:
q("""select distinct bowler_type from deliveries;""")

                                       bowler_type
0                                 Right arm Medium
1                             Left arm Fast medium
2                            Right arm Fast medium
3                           Slow Left arm Orthodox
4                                  Legbreak Googly
5                            Right arm Medium fast
6                                   Right arm Fast
7                                    Left arm Fast
8                                  Left arm Medium
9                             Left arm Medium fast
10                              Right arm Offbreak
11                                        Legbreak
12                             Left arm Wrist spin
13  Right arm Medium, Right arm Offbreak, Legbreak
14                    Right arm Offbreak, Legbreak
15             Right arm Offbreak, Legbreak Googly
16            Right arm Medium, Right arm Offbreak
17     Slow Left arm Orthodox, Left arm Wrist spin
18                           Right arm Fast Medium
19
20      Right arm Offbreak, Slow Left arm Orthodox
21                                             NaN

In [12]:
q("""select distinct season from matches;""")

     season
0      2008
1      2009
2      2010
3      2011
4      2012
5      2013
6      2014
7      2015
8      2016
9      2017
10     2018
11     2019
12  2020/21
13     2021
14     2022
15     2023
16     2024
17     2025
18     2026

In [13]:
q("""select distinct team_name from teams;""")

                      team_name
0   Royal Challengers Bangalore
1           Sunrisers Hyderabad
2                Mumbai Indians
3        Rising Pune Supergiant
4                 Gujarat Lions
5         Kolkata Knight Riders
6           Chennai Super Kings
7              Rajasthan Royals
8                Delhi Capitals
9                  Punjab Kings
10         Lucknow Super Giants
11               Gujarat Titans
12              Deccan Chargers
13         Kochi Tuskers Kerala
14                Pune Warriors
15      Rising Pune Supergiants

In [14]:
q("""select match_id,season_id,city,match_winner 
from matches
where match_winner ='Chennai Super Kings';""")

     match_id  season_id       city         match_winner
0     1136561       2018     Mumbai  Chennai Super Kings
1     1136565       2018    Chennai  Chennai Super Kings
2     1136577       2018       Pune  Chennai Super Kings
3     1136580       2018  Hyderabad  Chennai Super Kings
4     1136584       2018  Bengaluru  Chennai Super Kings
..        ...        ...        ...                  ...
141   1473494       2025    Kolkata  Chennai Super Kings
142   1473504       2025  Ahmedabad  Chennai Super Kings
143   1527691       2026    Chennai  Chennai Super Kings
144   1529265       2026    Chennai  Chennai Super Kings
145   1529276       2026     Mumbai  Chennai Super Kings

[146 rows x 4 columns]

In [15]:
q("""select match_id,season,city,venue
from matches
where season <=2015;""")

     match_id season        city                                       venue
0      335982   2008   Bangalore                       M Chinnaswamy Stadium
1      335983   2008  Chandigarh  Punjab Cricket Association Stadium, Mohali
2      335984   2008       Delhi                            Feroz Shah Kotla
3      335985   2008      Mumbai                            Wankhede Stadium
4      335986   2008     Kolkata                                Eden Gardens
..        ...    ...         ...                                         ...
512    829815   2015   Hyderabad   Rajiv Gandhi International Stadium, Uppal
513    829817   2015      Mumbai                            Wankhede Stadium
514    829819   2015        Pune     Maharashtra Cricket Association Stadium
515    829821   2015      Ranchi          JSCA International Stadium Complex
516    829823   2015     Kolkata                                Eden Gardens

[517 rows x 4 columns]

In [16]:
q("""select match_id,season,city,venue
from matches
where season >= 2015 AND city = 'Bangalore';""")

    match_id season       city                  venue
0     829719   2015  Bangalore  M Chinnaswamy Stadium
1     829737   2015  Bangalore  M Chinnaswamy Stadium
2     829745   2015  Bangalore  M Chinnaswamy Stadium
3     829763   2015  Bangalore  M Chinnaswamy Stadium
4     829771   2015  Bangalore  M Chinnaswamy Stadium
5     829785   2015  Bangalore  M Chinnaswamy Stadium
6     829813   2015  Bangalore  M Chinnaswamy Stadium
7     980907   2016  Bangalore  M Chinnaswamy Stadium
8     980921   2016  Bangalore  M Chinnaswamy Stadium
9     980959   2016  Bangalore  M Chinnaswamy Stadium
10    980969   2016  Bangalore  M Chinnaswamy Stadium
11    980981   2016  Bangalore  M Chinnaswamy Stadium
12    980987   2016  Bangalore  M Chinnaswamy Stadium
13    980999   2016  Bangalore  M Chinnaswamy Stadium
14    981013   2016  Bangalore  M Chinnaswamy Stadium
15    981019   2016  Bangalore  M Chinnaswamy Stadium
16   1082602   2017  Bangalore  M Chinnaswamy Stadium
17   1082607   2017  Bangalore  M Chinnaswamy Stadium
18   1082621   2017  Bangalore  M Chinnaswamy Stadium
19   1082633   2017  Bangalore  M Chinnaswamy Stadium
20   1082636   2017  Bangalore  M Chinnaswamy Stadium
21   1082648   2017  Bangalore  M Chinnaswamy Stadium
22   1082649   2017  Bangalore  M Chinnaswamy Stadium

In [17]:
q("""select match_id,season,city,venue
from matches
where season >= 2015 OR city = 'Bangalore';""")

,match_id,season,city,venue
0,335982,2008,Bangalore,M Chinnaswamy Stadium
1,1082591,2017,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
2,1082592,2017,Pune,Maharashtra Cricket Association Stadium
3,1082593,2017,Rajkot,Saurashtra Cricket Association Stadium
4,1082594,2017,Indore,Holkar Cricket Stadium
...,...,...,...,...
791,1529282,2026,Delhi,"Arun Jaitley Stadium, Delhi"
792,1529283,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...
793,1529284,2026,Mumbai,"Wankhede Stadium, Mumbai"
794,1529285,2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad"
795,1529286,2026,Jaipur,"Sawai Mansingh Stadium, Jaipur"

In [18]:
q("""SELECT match_winner,season
FROM matches
where season >= 2010 AND match_winner = 'Royal Challengers Bangalore';""")

                    match_winner season
0    Royal Challengers Bangalore   2010
1    Royal Challengers Bangalore   2010
2    Royal Challengers Bangalore   2010
3    Royal Challengers Bangalore   2010
4    Royal Challengers Bangalore   2010
..                           ...    ...
121  Royal Challengers Bangalore   2026
122  Royal Challengers Bangalore   2026
123  Royal Challengers Bangalore   2026
124  Royal Challengers Bangalore   2026
125  Royal Challengers Bangalore   2026

[126 rows x 2 columns]

In [19]:
q("""select match_id,city,venue 
from matches 
where season >= 2015 
order by city ;""")

,match_id,city,venue
0,1216493,NaN,Dubai International Cricket Stadium
1,1216495,NaN,Sharjah Cricket Stadium
2,1216496,NaN,Sharjah Cricket Stadium
3,1216498,NaN,Dubai International Cricket Stadium
4,1216500,NaN,Sharjah Cricket Stadium
...,...,...,...
749,1181767,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
750,1422131,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
751,1422134,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
752,1473441,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
753,1473447,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...

In [20]:
q("""select match_id,city,venue 
from matches 
where season >= 2015 
order by match_id DESC ;""")

,match_id,city,venue
0,1529286,Jaipur,"Sawai Mansingh Stadium, Jaipur"
1,1529285,Ahmedabad,"Narendra Modi Stadium, Ahmedabad"
2,1529284,Mumbai,"Wankhede Stadium, Mumbai"
3,1529283,New Chandigarh,Maharaja Yadavindra Singh International Cricke...
4,1529282,Delhi,"Arun Jaitley Stadium, Delhi"
...,...,...,...
749,829713,Kolkata,Eden Gardens
750,829711,Chennai,"MA Chidambaram Stadium, Chepauk"
751,829709,Pune,Maharashtra Cricket Association Stadium
752,829707,Chennai,"MA Chidambaram Stadium, Chepauk"
753,829705,Kolkata,Eden Gardens

In [21]:
q("""select match_id,city,venue 
from matches 
where season >= 2015 
order by match_id ASC ;""")

,match_id,city,venue
0,829705,Kolkata,Eden Gardens
1,829707,Chennai,"MA Chidambaram Stadium, Chepauk"
2,829709,Pune,Maharashtra Cricket Association Stadium
3,829711,Chennai,"MA Chidambaram Stadium, Chepauk"
4,829713,Kolkata,Eden Gardens
...,...,...,...
749,1529282,Delhi,"Arun Jaitley Stadium, Delhi"
750,1529283,New Chandigarh,Maharaja Yadavindra Singh International Cricke...
751,1529284,Mumbai,"Wankhede Stadium, Mumbai"
752,1529285,Ahmedabad,"Narendra Modi Stadium, Ahmedabad"
753,1529286,Jaipur,"Sawai Mansingh Stadium, Jaipur"

In [22]:
q("""select match_id,city,venue 
from matches 
where season >= 2015 
order by city ASC ;""")

,match_id,city,venue
0,1216493,NaN,Dubai International Cricket Stadium
1,1216495,NaN,Sharjah Cricket Stadium
2,1216496,NaN,Sharjah Cricket Stadium
3,1216498,NaN,Dubai International Cricket Stadium
4,1216500,NaN,Sharjah Cricket Stadium
...,...,...,...
749,1181767,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
750,1422131,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
751,1422134,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
752,1473441,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
753,1473447,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...

In [23]:
q("""select match_id,city,venue 
from matches 
where season >= 2015 
order by city DESC ;""")

,match_id,city,venue
0,829727,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
1,829731,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
2,829743,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
3,980973,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
4,980979,Visakhapatnam,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
...,...,...,...
749,1216544,NaN,Dubai International Cricket Stadium
750,1216546,NaN,Dubai International Cricket Stadium
751,1216547,NaN,Dubai International Cricket Stadium
752,1237177,NaN,Dubai International Cricket Stadium
753,1237181,NaN,Dubai International Cricket Stadium

In [24]:
q("""SELECT COUNT(DISTINCT venue) AS venue
FROM matches""")

   venue
0     59

In [25]:
q("""SELECT COUNT(*) AS matches
FROM matches""")

   matches
0     1212

In [26]:
q("""SELECT venue, COUNT(*) AS match_count
FROM matches
GROUP BY venue""")

                                                venue  match_count
0                                Arun Jaitley Stadium           14
1                         Arun Jaitley Stadium, Delhi           27
2                                    Barabati Stadium            7
3                 Barsapara Cricket Stadium, Guwahati            8
4   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...           26
5                                   Brabourne Stadium           10
6                           Brabourne Stadium, Mumbai           17
7                                        Buffalo Park            3
8                               De Beers Diamond Oval            3
9                          Dr DY Patil Sports Academy           17
10                 Dr DY Patil Sports Academy, Mumbai           20
11  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...           13
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...            4
13                Dubai International Cricket Stadium           46
14                                       Eden Gardens           77
15                              Eden Gardens, Kolkata           27
16                                   Feroz Shah Kotla           60
17                                         Green Park            4
18       Himachal Pradesh Cricket Association Stadium            9
19  Himachal Pradesh Cricket Association Stadium, ...            6
20                             Holkar Cricket Stadium            9
21                 JSCA International Stadium Complex            7
22                                          Kingsmead           15
23                              M Chinnaswamy Stadium           65
24                   M Chinnaswamy Stadium, Bengaluru           24
25                              M.Chinnaswamy Stadium           15
26                             MA Chidambaram Stadium            9
27                    MA Chidambaram Stadium, Chepauk           48
28           MA Chidambaram Stadium, Chepauk, Chennai           38
29  Maharaja Yadavindra Singh International Cricke...           10
30  Maharaja Yadavindra Singh International Cricke...            5
31            Maharashtra Cricket Association Stadium           22
32      Maharashtra Cricket Association Stadium, Pune           13
33                   Narendra Modi Stadium, Ahmedabad           37
34                                      Nehru Stadium            5
35                              New Wanderers Stadium            8
36                                           Newlands            7
37                                    OUTsurance Oval            2
38       Punjab Cricket Association IS Bindra Stadium           10
39  Punjab Cricket Association IS Bindra Stadium, ...           11
40  Punjab Cricket Association IS Bindra Stadium, ...            5
41         Punjab Cricket Association Stadium, Mohali           35
42                 Rajiv Gandhi International Stadium           15
43          Rajiv Gandhi International Stadium, Uppal           49
44  Rajiv Gandhi International Stadium, Uppal, Hyd...           23
45                       Sardar Patel Stadium, Motera           12
46             Saurashtra Cricket Association Stadium           10
47                             Sawai Mansingh Stadium           47
48                     Sawai Mansingh Stadium, Jaipur           19
49   Shaheed Veer Narayan Singh International Stadium            6
50                            Sharjah Cricket Stadium           28
51                               Sheikh Zayed Stadium           29
52                                   St George's Park            7
53                         Subrata Roy Sahara Stadium           16
54                                    SuperSport Park           12
55       Vidarbha Cricket Association Stadium, Jamtha            3
56                                   Wankhede Stadium           73
57                           Wankhede Stadium, Mumbai           57
58                   Zayed Cricket Stadium, Abu Dhabi            8

In [27]:
q("""SELECT match_Winner, COUNT(*) AS WINNER
FROM matches
GROUP BY match_Winner
ORDER BY WINNER DESC""")

                   match_winner  WINNER
0                Mumbai Indians     155
1           Chennai Super Kings     146
2   Royal Challengers Bangalore     139
3         Kolkata Knight Riders     137
4           Sunrisers Hyderabad     132
5                  Punjab Kings     130
6                Delhi Capitals     126
7              Rajasthan Royals     125
8                Gujarat Titans      42
9          Lucknow Super Giants      33
10       Rising Pune Supergiant      15
11                Pune Warriors      13
12                Gujarat Lions      13
13         Kochi Tuskers Kerala       6

In [28]:
q("""SELECT bowler,COUNT(*) AS delivery_count
FROM deliveries
GROUP BY bowler
HAVING delivery_count > 1000;""")

               bowler  delivery_count
0            A Mishra            3444
1             A Nehra            1974
2            A Nortje            1169
3            AB Dinda            1589
4          AD Russell            1885
..                ...             ...
80           VR Aaron            1065
81  Washington Sundar            1162
82          YK Pathan            1184
83          YS Chahal            4068
84             Z Khan            2276

[85 rows x 2 columns]

In [29]:
q("""select lower(bowler), count(*) as deliveries
from deliveries
group by lower(bowler)""")

      lower(bowler)  deliveries
0    a ashish reddy         270
1          a badoni          41
2        a chandila         234
3       a choudhary         108
4       a dananjaya          25
..              ...         ...
563       ys chahal        4068
564   yudhvir singh         145
565    yuvraj singh         882
566          z khan        2276
567  zeeshan ansari         209

[568 rows x 2 columns]

In [30]:
q("""select venue, count(*) as matches
from matches
WHERE venue ='Buffalo park' OR venue ='Eden Gardens'
group by venue""")

          venue  matches
0  Eden Gardens       77

In [31]:
q("""SELECT batter, COUNT(*) AS deliveries
FROM deliveries
GROUP BY batter
ORDER BY deliveries DESC;""")

             batter  deliveries
0           V Kohli        6942
1         RG Sharma        5561
2          S Dhawan        5483
3         DA Warner        4849
4         AM Rahane        4259
..              ...         ...
722     Sunny Gupta           1
723          U Kaul           1
724  V Pratap Singh           1
725   Y Prithvi Raj           1
726      YA Abdulla           1

[727 rows x 2 columns]

In [32]:
q("""
SELECT m.match_id, m.city, m.venue
FROM matches AS m
JOIN venues AS v
ON m.venue = v.venue
""")

,match_id,city,venue
0,335982,Bangalore,M Chinnaswamy Stadium
1,1082591,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
2,1082592,Pune,Maharashtra Cricket Association Stadium
3,1082593,Rajkot,Saurashtra Cricket Association Stadium
4,1082594,Indore,Holkar Cricket Stadium
...,...,...,...
1311,1529282,Delhi,"Arun Jaitley Stadium, Delhi"
1312,1529283,New Chandigarh,Maharaja Yadavindra Singh International Cricke...
1313,1529284,Mumbai,"Wankhede Stadium, Mumbai"
1314,1529285,Ahmedabad,"Narendra Modi Stadium, Ahmedabad"
1315,1529286,Jaipur,"Sawai Mansingh Stadium, Jaipur"

In [33]:
q("""select d.batter, p.bat_style
from deliveries as d
join players as p on p.player_name = d.batter
""")

            batter       bat_style
0       MN Samuels  Right hand Bat
1       MN Samuels  Right hand Bat
2       MN Samuels  Right hand Bat
3       MN Samuels  Right hand Bat
4       MN Samuels  Right hand Bat
...            ...             ...
288221      N Rana   Left hand Bat
288222      N Rana   Left hand Bat
288223      N Rana   Left hand Bat
288224   SU Parakh   Left hand Bat
288225   SU Parakh   Left hand Bat

[288226 rows x 2 columns]

In [34]:
q("""
SELECT venue
FROM venues
EXCEPT
SELECT DISTINCT venue
FROM matches
""")

Empty DataFrame
Columns: [venue]
Index: []

In [35]:
q("""SELECT count(distinct batter)
FROM deliveries
WHERE batter not in (SELECT player_name FROM players);""")

   count(distinct batter)
0                       0

In [36]:
q("""select count(*) as total ,
sum(case when city is null then 1 else 0 end) as missing
from matches""")

   total  missing
0   1212       51

In [37]:
q("""select count(*) as total ,
sum(case when city is null then 1 else 0 end) as missing
from venues""")

   total  missing
0     63        2

In [38]:
q("""select count(distinct venue) as venues 
from matches""")

   venues
0      59

In [39]:
q("""
SELECT
    COUNT(*) AS total,
    SUM(CASE WHEN city IS NULL THEN 1 ELSE 0 END) AS null_count,
    SUM(CASE WHEN city ='' THEN 1 ELSE 0 END) AS empty_count , 
    SUM(CASE WHEN TRIM(city) ='' AND city <> '' THEN 1 ELSE 0 END) AS spaces
FROM matches;""")

   total  null_count  empty_count  spaces
0   1212          51            0       0

In [40]:
q("""select count (distinct
case when instr(venue,',')>0
then trim(substr(venue,1,instr(venue,',')-1))
else trim (venue)end) as after_coma
from matches;""")

   after_coma
0          42

In [41]:
q("""select count (distinct venue) as distinct_venue
from matches;""")

   distinct_venue
0              59

In [42]:
q("""select count(*) as rows,
count (distinct venue) as distinct_venues
from venues;""")

   rows  distinct_venues
0    63               59

In [43]:
q("""select venue,count(*) as n
from venues
group by venue
having count(*) > 1;""")

                                               venue  n
0                 Dr DY Patil Sports Academy, Mumbai  2
1                Dubai International Cricket Stadium  2
2  Maharaja Yadavindra Singh International Cricke...  2
3                            Sharjah Cricket Stadium  2

In [44]:
q("""select result,count(*) as n
from matches
group by result;""")

      result     n
0  no result     9
1        tie    16
2        win  1187

In [45]:
select match_id,season,result,match_winner
from matches
where result = 'no result' ;

SyntaxError: invalid syntax (1577607555.py, line 1)